### ISSUE TITLE
Bug report N°1 : "no-header" metadata cause a border stacking.

### ISSUE THREAD

**Issue by NoahBoos** [NoahBoos/Callouts-enhancements-for-Obsidian#1]
# What's the bug ?
When a callout wear "no-header" metadata, the top border of the callout stack with the top border of the callouts content.

# How to Reproduce
Step-by-step walk through on how to reproduce this bug.
- Create a Callout using the `no-header` metadata.
- Observe.

# Expected behavior
Those two borders shouldn't stack, instead, the border of the Callout content should disappear.

# How to patch it ?
Simply select the Callout content of a Callout wearing `no-header` and disable the `border-top` property using `border-top: none` or `border: none`.

# Screenshots
![image](https://github.com/NoahBoos/Callouts-enhancements-for-Obsidian/assets/130183121/02dd06c1-b5b4-47f3-aa97-e3ca5e62da14)

# Additional context
I've met this bug while I was developing this CSS Suite.

**Comment by NoahBoos** [comment]
# Patched - 12/05/2024 01:06
```css
.callout[data-callout-metadata~="no-header"] > .callout-content,
.callout[data-callout-metadata~="sans-en-tete"] > .callout-content {
    border-top: none;
}
```
